name: 查重
on: [push, pull_request]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Run Checker
        run: |
          ls
          go mod tidy
          go run check_dulplicate.go 5
